common_words = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "is", "are", "was", "were", "been", "has", "had", "did", "do", "does",
    "doing", "done", "am", "being", "having", "can", "could", "shall", "should", "will",
    "would", "may", "might", "must", "ought", "a", "an", "the", "and", "but",
    "or", "nor", "for", "so", "yet", "at", "by", "in", "of", "on",
    "to", "up", "with", "as", "if", "than", "because", "since", "so", "although",
    "though", "while", "whereas", "after", "before", "once", "until", "when", "whenever", "while",
    "where", "wherever", "whether", "that", "which", "who", "whom", "whose", "what", "whatever",
    "which", "whichever", "whoever", "whomever", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "each", "every", "either", "neither", "some",
    "any", "no", "one", "another", "such", "other", "more", "most", "many", "much",
    "few", "several", "all", "both", "half", "some", "any", "no", "none", "one",
    "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth",
    "next", "last", "previous", "other", "another", "such", "what", "which", "who", "whom",
    "whose", "this", "that", "these", "those", "my", "your", "his", "her", "its",
    "our", "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same", "other", "another", "such", "what", "which", "who", "whom", "whose",
    "this", "that", "these", "those", "my", "your", "his", "her", "its", "our",
    "their", "own", "same", "other", "another", "such", "what", "which", "who",
    "whom", "whose", "this", "that", "these", "those", "my", "your", "his", "her",
    "its", "our", "their", "own", "same", "other", "another", "such", "what", "which",
    "who", "whom", "whose", "this", "that", "these", "those", "my", "your", "his",
    "her", "its", "our", "their", "own", "same", "other", "another", "such", "what",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "my", "your",
    "his", "her", "its", "our", "their", "own", "same", "other", "another", "such",
    "what", "which", "who", "whom", "whose", "this", "that", "these", "those", "my",
    "your", "his", "her", "its", "our", "their", "own", "same", "other", "another",
    "such", "what", "which", "who", "whom", "whose", "this", "that", "these", "those",
    "my", "your", "his", "her", "its", "our", "their", "own", "same", "other",
    "another", "such", "what", "which", "who", "whom", "whose", "this", "that",
    "these", "those", "my", "your", "his", "her", "its", "our", "their", "own",
    "same"
]
